apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azuredisk-custom-storageclass
  resources:
    requests:
      storage: 1Gi